
 {
function fviuDelete(sName,oLink){var $this=this;var oDate=new Date()}
function fvtTogglePopup(sName,oLink){var oPopup=$(oLink).parents('.bx-form-input-translator:first').find('#bx-form-field-translator-popup-'+sName);if(oPopup.filter(':visible').length>0){oPopup.dolPopupHide();return}
oPopup.dolPopup({moveToDocRoot:!1,pointer:{el:$(oLink)}})};function fvtSelectLanguage(sName,sLangName,oLink){var oTranslator=$(oLink).parents('.bx-form-input-translator:first');var sId='#bx-form-language-'+sName+'-'+sLangName;$(oLink).parent().siblings('.active:visible').hide().siblings('.not-active:hidden').show().siblings(sId+'-pas:visible').hide().siblings(sId+'-act:hidden').show();oTranslator.find('.bx-form-input-language-current').css('background-image',$(oLink).parent('.bx-form-input-language').css('background-image')).find('a').html($(oLink).html());oTranslator.find('#bx-form-field-translator-popup-'+sName).dolPopupHide();$(oLink).parents('#bx-form-element-'+sName+':first').find('.bx-form-input-translation:visible').hide().siblings('.bx-form-input-translation-'+sName+'-'+sLangName+':hidden').show()}
 }

 {
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('2.W=b(7){7=2.R({y:o,L:o,K:Y,x:o,A:o,n:o,J:Y},7);g(7.y){g(2.V(7.A)&&2.m(7.n)===\'o\'){7.n=b(M,z,e){7.A(z,e)}}D g(2.m(7.A)===2.m(7.n)===\'o\'){7.n=b(M,z,e){1j.X&&X.1i(\'W 1h 1g 1f h\',M,z,e)}}1e $.1d({m:\'1c\',y:7.y,L:7.L,K:7.K,1b:(2.T.S)?"6":"4",x:b(4){f h=k I(4);g(2.V(7.x))7.x(h)},n:7.n,J:7.J})}};b I(4){g(4)3.U(4)};I.v={m:\'\',p:\'\',d:\'\',c:\'\',j:\'\',U:b(4){g(2.T.S){f H=k 1a("19.18");H.17(4);4=H}g(2(\'9\',4).E==1){3.m=\'C\';f w=k F(4)}D g(2(\'h\',4).E==1){3.m=\'16\';f w=k G(4)}g(w)2.R(3,w)}};b s(){};s.v={d:\'\',c:\'\',j:\'\',l:\'\',r:\'\'};b G(4){3.u(4)};G.v={u:b(4){f 9=2(\'h\',4).a(0);3.p=\'1.0\';3.d=2(9).5(\'d:i\').6();3.c=2(9).5(\'c:i\').t(\'Q\');3.j=2(9).5(\'15:i\').6();3.B=2(9).t(\'4:14\');3.l=2(9).5(\'l:i\').6();3.q=k P();f h=3;2(\'13\',4).O(b(){f 8=k s();8.d=2(3).5(\'d\').a(0).6();8.c=2(3).5(\'c\').a(0).t(\'Q\');8.j=2(3).5(\'12\').a(0).6();8.l=2(3).5(\'l\').a(0).6();8.r=2(3).5(\'r\').a(0).6();h.q.N(8)})}};b F(4){3.u(4)};F.v={u:b(4){g(2(\'C\',4).E==0)3.p=\'1.0\';D 3.p=2(\'C\',4).a(0).t(\'p\');f 9=2(\'9\',4).a(0);3.d=2(9).5(\'d:i\').6();3.c=2(9).5(\'c:i\').6();3.j=2(9).5(\'j:i\').6();3.B=2(9).5(\'B:i\').6();3.l=2(9).5(\'11:i\').6();3.q=k P();f h=3;2(\'8\',4).O(b(){f 8=k s();8.d=2(3).5(\'d\').a(0).6();8.c=2(3).5(\'c\').a(0).6();8.j=2(3).5(\'j\').a(0).6();8.l=2(3).5(\'10\').a(0).6();8.r=2(3).5(\'Z\').a(0).6();h.q.N(8)})}};',62,82,'||jQuery|this|xml|find|text|options|item|channel|eq|function|link|title||var|if|feed|first|description|new|updated|type|error|null|version|items|id|JFeedItem|attr|_parse|prototype|feedClass|success|url|msg|failure|language|rss|else|length|JRss|JAtom|xmlDoc|JFeed|global|cache|data|xhr|push|each|Array|href|extend|msie|browser|parse|isFunction|getFeed|console|true|guid|pubDate|lastBuildDate|content|entry|lang|subtitle|atom|loadXML|XMLDOM|Microsoft|ActiveXObject|dataType|GET|ajax|return|load|to|failed|log|window'.split('|')))
 }

 {
(function($){$.fn.dolRSSFeed=function(oOptions){var oOptions=oOptions||{};return this.each(function(){var $Cont=$(this);var sRSSObject=$Cont.attr('rssobject');var iRSSID=$Cont.attr('rssid');if((!iRSSID||!sRSSObject)&&oOptions.forceUrl==undefined)
return!1;var iMaxNum=parseInt($Cont.attr('rssnum')||0);var iMemID=parseInt($Cont.attr('member')||0);var sFeedURL=(oOptions.forceUrl!=undefined)?oOptions.forceUrl:sUrlRoot+'get_rss_feed.php?object='+sRSSObject+'&id='+iRSSID+'&member='+iMemID;bx_loading_content($(this),!0,!0);if('undefined'===typeof(jQuery.browser))
jQuery.browser={"msie":!1};$.getFeed({url:sFeedURL,error:function(oResponse){if(typeof oOptions.onError=='function')
oOptions.onError();},success:function(feed){if(feed==undefined||!feed.items)
return;if(typeof oOptions.onLoad=='function')
oOptions.onLoad();var sCode='<div class="sys-rss-feed-wrapper bx-def-bc-margin bx-def-padding-sec-top">';var sTarget,iCount=0;for(var iItemId=0;iItemId<feed.items.length;iItemId ++){var item=feed.items[iItemId];var sDate='',oDate,a;if(null!=(a=item.updated.match(/(\d+)-(\d+)-(\d+)T(\d+):(\d+):(\d+)Z/))){oDate=new Date(a[1],a[2]-1,a[3],a[4],a[5],a[6],0);sDate=oDate.toLocaleString()}else if(item.updated.length>0){oDate=new Date(item.updated.replace(/z$/i,"-00:00"));sDate=isNaN(oDate)?'':oDate.toLocaleString()}
sTarget='';if(item.link.substring(0,sUrlRoot.length)!=sUrlRoot)
sTarget='target="_blank"';sCode+='<div class="sys-rss-item-wrapper">'+'<div class="sys-rss-item-header bx-def-font-h2">'+'<a href="'+item.link+'" '+sTarget+'>'+item.title+'</a>'+'</div>'+'<div class="sys-rss-item-desc">'+item.description+'</div>'+'<div class="sys-rss-item-info bx-def-font-small bx-def-font-grayed">'+'<span>'+sDate+'</span>'+'</div>'+'</div>'+'<hr class="bx-def-hr bx-def-margin-sec-top bx-def-margin-sec-bottom" />';iCount ++;if(iCount==iMaxNum)
break}
sTarget='';if(feed.link.substring(0,sUrlRoot.length)!=sUrlRoot)
sTarget='target="_blank"';sCode+='</div>'+'<div class="sys-rss-read-more">'+'<i class="sys-icon link"></i><a href="'+feed.link+'" '+sTarget+' class="bx-def-margin-sec-left sys-rss-read-more-link">'+feed.title+'</a>'+'</div>';$Cont.hide().html(sCode);if(typeof oOptions.onBeforeShow=='function')
oOptions.onBeforeShow();$Cont.show();if(typeof oOptions.onShow=='function')
oOptions.onShow();}})})}})(jQuery)
 }

 {
function BxDolStudioPage(oOptions){this.sActionsUrl=oOptions.sActionUrl;this.sObjName=oOptions.sObjName==undefined?'oBxDolStudioPage':oOptions.sObjName;this.sAnimationEffect=oOptions.sAnimationEffect==undefined?'slide':oOptions.sAnimationEffect;this.iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed;this.oPopupOptions={fog:{color:'#fff',opacity:.7},closeOnOuterClick:!1}}
BxDolStudioPage.prototype.processJson=function(oData){bx_loading('bx-std-page-columns',!1);processJsonData(oData)};BxDolStudioPage.prototype.togglePopup=function(sName,oLink){var $this=this;var sId='#bx-std-pcap-menu-popup-'+sName;if($(sId+':visible').length>0){$(sId).dolPopupHide();return}
$(oLink).parent().addClass('bx-menu-tab-active');var oPopupOptions={pointer:{el:$(oLink)},onHide:function(){$(oLink).parent().removeClass('bx-menu-tab-active')}};switch(sName){case 'help':oPopupOptions=$.extend({},oPopupOptions,{onBeforeShow:function(){var oPopup=$(sId);var oPopupRss=oPopup.find('.RSSAggrCont');if(oPopupRss.contents().length)
return;oPopupRss.dolRSSFeed({onError:function(){oPopupRss.html(_t('_adm_txt_show_help_content_empty'));oPopup._dolPopupSetPosition(oPopupOptions)},onShow:function(){oPopup._dolPopupSetPosition(oPopupOptions)}});oPopup._dolPopupSetPosition(oPopupOptions)}});break}
if($(sId).html().length>0)
$(sId).dolPopup(oPopupOptions);}
 }

 {
function BxDolStudioDesigner(oOptions){this.sActionsUrl=oOptions.sActionUrl;this.sObjName=oOptions.sObjName==undefined?'oBxDolStudioDesigner':oOptions.sObjName;this.sParamPrefix=oOptions.sParamPrefix==undefined?'dsg':oOptions.sParamPrefix;this.sAnimationEffect=oOptions.sAnimationEffect==undefined?'fade':oOptions.sAnimationEffect;this.iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed;this.sCodeMirror=oOptions.sCodeMirror==undefined?'':oOptions.sCodeMirror;var $this=this;$(document).ready(function(){if($this.sCodeMirror!='')
$this.initCodeMirror($this.sCodeMirror);})}
BxDolStudioDesigner.prototype.initCodeMirror=function(sSelector){var oSelector=$(sSelector);for(var i=0;i<oSelector.length;i++){var e=CodeMirror.fromTextArea(oSelector.get(i),{lineNumbers:!0,mode:"htmlmixed",htmlMode:!0,matchBrackets:!0})}};BxDolStudioDesigner.prototype.makeDefault=function(sUri){var $this=this;var oDate=new Date();var aParams={_t:oDate.getTime()};aParams[this.sParamPrefix+'_action']='make_default';aParams[this.sParamPrefix+'_value']=sUri;$.post(this.sActionsUrl,aParams,function(oData){if(oData.code!=0&&oData.message.length>0){bx_alert(oData.message);return}
document.location.href=document.location.href},'json')};BxDolStudioDesigner.prototype.deleteIcon=function(sName){var $this=this;var oDate=new Date();var aParams={_t:oDate.getTime()};aParams[this.sParamPrefix+'_action']='delete_icon';aParams[this.sParamPrefix+'_value']=sName;$.post(this.sActionsUrl,aParams,function(oData){if(oData.code!=0&&oData.message.length>0){bx_alert(oData.message);return}
$('.adm-dsg-ip-'+sName).bx_anim('hide',$this.sAnimationEffect,$this.iAnimationSpeed,function(){$(this).remove()})},'json')};BxDolStudioDesigner.prototype.deleteCover=function(sType,iId){var $this=this;var oDate=new Date();var aParams={_t:oDate.getTime()};aParams[this.sParamPrefix+'_action']='delete_cover';aParams[this.sParamPrefix+'_value']=sType;$.post(this.sActionsUrl,aParams,function(oData){if(oData.code!=0&&oData.message.length>0){bx_alert(oData.message);return}
$('#bx-dsg-cover-'+iId).bx_anim('hide',$this.sAnimationEffect,$this.iAnimationSpeed,function(){$(this).remove()})},'json')}
 }

 {
function BxDolStudioOptions(oOptions){this.sActionsUrl=oOptions.sActionUrl;this.sObjName=oOptions.sObjName==undefined?'oBxDolStudioOptions':oOptions.sObjName;this.sParamPrefix=oOptions.sParamPrefix==undefined?'opt':oOptions.sParamPrefix;this.sType=oOptions.sType==undefined?'':oOptions.sType;this.sCategory=oOptions.sCategory==undefined?'':oOptions.sCategory;this.sMix=oOptions.sMix==undefined?'':oOptions.sMix;this.sAnimationEffect=oOptions.sAnimationEffect==undefined?'fade':oOptions.sAnimationEffect;this.iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed;this.bBusy=!1}
BxDolStudioOptions.prototype.onSubmit=function(oForm){if(this.bBusy)
return!1;var oSubmit=$(oForm).find('input[type="submit"],button[type="submit"]');oSubmit.addClass('bx-btn-disabled');bx_loading_btn(oSubmit,!0);return(this.bBusy=!0)};BxDolStudioOptions.prototype.onSubmitted=function(sFormId,sTocken,oData){var oForm=$('#'+sFormId);var oSubmit=oForm.find('input[type="submit"],button[type="submit"]');oForm.find('input[name="csrf_token"]').val(sTocken);oSubmit.removeClass('bx-btn-disabled');bx_loading_btn(oSubmit,!1);this.bBusy=!1};BxDolStudioOptions.prototype.import=function(oButton){this.mixAction(oButton,'import')};BxDolStudioOptions.prototype.onImport=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.export=function(oButton){this.mixAction(oButton,'export')};BxDolStudioOptions.prototype.onExport=function(oData){document.location.href=oData.url};BxDolStudioOptions.prototype.mixCreate=function(oButton){this.mixActionWithValue(oButton,'create-mix')};BxDolStudioOptions.prototype.onMixCreate=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixImport=function(oButton){this.mixActionWithValue(oButton,'import-mix')};BxDolStudioOptions.prototype.onMixImport=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixSelect=function(oSelect){this.mixActionWithValue(oSelect,'select-mix',$(oSelect).val())};BxDolStudioOptions.prototype.onMixSelect=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixExport=function(oButton,iId){this.mixActionWithValue(oButton,'export-mix',iId)};BxDolStudioOptions.prototype.onMixExport=function(oData){document.location.href=oData.url};BxDolStudioOptions.prototype.mixPublish=function(oButton,iId){this.mixActionWithValue(oButton,'publish-mix',iId)};BxDolStudioOptions.prototype.onMixPublish=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixHide=function(oButton,iId){this.mixActionWithValue(oButton,'hide-mix',iId)};BxDolStudioOptions.prototype.onMixHide=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixDelete=function(oButton,iId){this.mixActionWithValue(oButton,'delete-mix',iId,1)};BxDolStudioOptions.prototype.onMixDelete=function(oData){document.location.href=document.location.href};BxDolStudioOptions.prototype.mixAction=function(oSource,sAction,bConfirm){var $this=this;var oDate=new Date();var aParams={type:this.sType,category:this.sCategory,_t:oDate.getTime()};aParams[this.sParamPrefix+'_action']=sAction;var oPerform=function(){$.post(this.sActionsUrl,aParams,function(oData){processJsonData(oData)},'json')};if(bConfirm!=undefined&&parseInt(bConfirm)==1)
bx_confirm('',oPerform);else oPerform()};BxDolStudioOptions.prototype.mixActionWithValue=function(oSource,sAction,mixedValue,bConfirm){var $this=this;var oDate=new Date();var aParams={type:$this.sType,category:$this.sCategory,_t:oDate.getTime()};aParams[this.sParamPrefix+'_action']=sAction;aParams[this.sParamPrefix+'_value']=mixedValue;var oPerform=function(){$.post($this.sActionsUrl,aParams,function(oData){processJsonData(oData)},'json')};if(bConfirm!=undefined&&parseInt(bConfirm)==1)
bx_confirm('',oPerform);else oPerform()};BxDolStudioOptions.prototype.processResult=function(oData){processJsonData(oData)}
 }

 {
function BxDolStudioLauncher(oOptions){this.sActionsUrl=oOptions.sActionUrl;this.sObjName=oOptions.sObjName==undefined?'oBxDolStudioLauncher':oOptions.sObjName;this.sAnimationEffect=oOptions.sAnimationEffect==undefined?'fade':oOptions.sAnimationEffect;this.iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'fast':oOptions.iAnimationSpeed;this.bInit=oOptions.bInit==undefined?!0:oOptions.bInit;this.aJitterConf={item:'.bx-std-widget-icon',elements:'.bx-std-widget-actions,.bx-std-widget-icon-jitter,.bx-std-widget-caption-jitter'};this.aSortingConf={parent:'.bx-std-widgets',item:'.bx-std-widget',placeholder:'bx-std-widget bx-std-widget-empty'};if(this.bInit)
this.init();}
BxDolStudioLauncher.prototype.init=function(){var $this=this;$(document).ready(function(){$($this.aSortingConf.parent).sortable({disabled:!0,handle:'.bx-std-widget-icon-jitter > img',items:$this.aSortingConf.item,placeholder:$this.aSortingConf.placeholder,start:function(oEvent,oUi){oUi.item.addClass('bx-std-widget-dragging')},stop:function(oEvent,oUi){oUi.item.removeClass('bx-std-widget-dragging');$this.reorder(oUi.item)}});if($this._isFeatured())
$('.bx-menu-tab-featured').addClass('bx-menu-tab-active');})};BxDolStudioLauncher.prototype.browser=function(oLink,sType){var $this=this;var oDate=new Date();if(sType==undefined)
sType='';var oBrowser=$('#bx-std-launcher-browser');if(oBrowser.length>0){var fBrowserShow=function(){oBrowser.dolPopup({closeOnOuterClick:!0,pointer:{el:'.bx-menu-breadcrumb .bx-menu-bc-'+(sType.length>0?'type':'home'),align:'left',offset:'-16 0'},onBeforeShow:function(oPopup){$this.browserChangeType(oLink,sType)}})}
if(oBrowser.is(':visible'))
oBrowser.dolPopupHide({onHide:function(){if(oBrowser.find('.bx-std-lb-menu .bx-std-pmen-item.bx-std-pmen-item-'+sType+'.bx-menu-tab-active').length==0)
fBrowserShow();}});else fBrowserShow();return!1}
$.get(this.sActionsUrl,{action:'launcher-browser',type:sType,_t:oDate.getTime()},function(oData){processJsonData(oData)},'json');return!1};BxDolStudioLauncher.prototype.browserChangeType=function(oLink,sType){var sMenuActive='bx-menu-tab-active';var sContentActive='bx-std-lbw-active';var oMenuActive=$('.bx-std-launcher-browser .bx-std-lb-menu .bx-std-pmen-item.'+sMenuActive);if(oMenuActive.hasClass('bx-std-pmen-item-'+sType))
return;oMenuActive.removeClass(sMenuActive).siblings('.bx-std-pmen-item-'+sType).addClass(sMenuActive);$('.bx-std-launcher-browser .bx-std-lb-content .bx-std-lb-widgets.'+sContentActive).removeClass(sContentActive).siblings('.bx-std-lbw-'+sType).addClass(sContentActive)};BxDolStudioLauncher.prototype.updateCache=function(){var oDate=new Date();$.get(this.sActionsUrl,{action:'launcher-update-cache',_t:oDate.getTime()})};BxDolStudioLauncher.prototype.reorder=function(oDraggable){var oDate=new Date();$.post(this.sActionsUrl+'?'+oDraggable.parent('.bx-std-widgets').sortable('serialize',{key:'items[]'}),{action:'launcher-reorder',page:this.sScrollCurrent,_t:oDate.getTime()},function(oData){if(oData.code!=0){bx_alert(oData.message);return}},'json');return!0};BxDolStudioLauncher.prototype.featured=function(sPageName,oLink){var $this=this;var oDate=new Date();$.get(this.sActionsUrl,{action:'page-featured',page:sPageName,_t:oDate.getTime()},function(oData){$('.bx-popup-applied:visible').dolPopupHide();if(oData.code!=0){bx_alert(oData.message);return}
var oSettings=$(oLink).parents('.bx-mod-popup-settings:first');if(oSettings.length>0&&oData.widget_id!=undefined&&oData.widget.length>0){$('#bx-std-widget-'+oData.widget_id).replaceWith(oData.widget);if($this.bInit)
oBxDolStudioLauncher.enableJitter();}},'json');return!0};BxDolStudioLauncher.prototype.bookmark=function(sPageName,oLink){var oDate=new Date();$.get(this.sActionsUrl,{action:'page-bookmark',page:sPageName,_t:oDate.getTime()},function(oData){$('.bx-popup-applied:visible').dolPopupHide();if(oData.code!=0){bx_alert(oData.message);return}},'json');return!0};BxDolStudioLauncher.prototype.rearrange=function(iWidgetId,oSelect){var oDate=new Date();var oSelect=$(oSelect);var oPopup=oSelect.parents('.bx-popup');bx_loading(oPopup,!0);$.get(this.sActionsUrl,{action:'widget-rearrange',widget_id:iWidgetId,type:oSelect.val(),_t:oDate.getTime()},function(oData){bx_loading(oPopup,!1);processJsonData(oData)},'json');return!0};BxDolStudioLauncher.prototype.enableJitter=function(){this._disableFeatured();$('.bx-menu-tab-featured').removeClass('bx-menu-tab-active');$(this.aJitterConf.elements).fadeIn('fast');$(this.aJitterConf.item).removeClass('bx-std-widget-icon-trans');$(this.aSortingConf.parent).sortable('option','disabled',!1)};BxDolStudioLauncher.prototype.disableJitter=function(){$(this.aJitterConf.elements).fadeOut('fast');$(this.aJitterConf.item).addClass('bx-std-widget-icon-trans');$(this.aSortingConf.parent).sortable('option','disabled',!0)};BxDolStudioLauncher.prototype.enableFeatured=function(){this.disableJitter();$('.bx-menu-tab-edit').removeClass('bx-menu-tab-active');$.cookie('bx_studio_featured','1',{path:'/'});this._enableFeatured()};BxDolStudioLauncher.prototype.disableFeatured=function(){$.cookie('bx_studio_featured','0',{path:'/'});this._disableFeatured()};BxDolStudioLauncher.prototype._isFeatured=function(){return parseInt($.cookie('bx_studio_featured'))==1};BxDolStudioLauncher.prototype._enableFeatured=function(){var $this=this;$('.bx-std-widget:not(.bx-std-widget-icon-featured)').bx_anim('hide',this.sAnimationEffect,this.iAnimationSpeed)};BxDolStudioLauncher.prototype._disableFeatured=function(){var $this=this;$('.bx-std-widget:not(.bx-std-widget-icon-featured)').bx_anim('show',this.sAnimationEffect,this.iAnimationSpeed)}
 }

 {
function BxDolStudioMenuTop(oOptions){this.sActionsUrl=oOptions.sActionUrl;this.sObjName=oOptions.sObjName==undefined?'oBxDolStudioMenuTop':oOptions.sObjName;this.sAnimationEffect=oOptions.sAnimationEffect==undefined?'slide':oOptions.sAnimationEffect;this.iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed}
BxDolStudioMenuTop.prototype.clickEdit=function(oItem){$('.bx-popup-applied:visible').dolPopupHide();var oParent=$(oItem).parent();if(oParent.hasClass('bx-menu-tab-active')){oParent.removeClass('bx-menu-tab-active');oBxDolStudioLauncher.disableJitter()}else{oParent.addClass('bx-menu-tab-active');oBxDolStudioLauncher.enableJitter()}};BxDolStudioMenuTop.prototype.clickFeatured=function(oItem){$('.bx-popup-applied:visible').dolPopupHide();var oParent=$(oItem).parent();if(oParent.hasClass('bx-menu-tab-active')){oParent.removeClass('bx-menu-tab-active');oBxDolStudioLauncher.disableFeatured()}else{oParent.addClass('bx-menu-tab-active');oBxDolStudioLauncher.enableFeatured()}};BxDolStudioMenuTop.prototype.clickLogout=function(oItem){$(oItem).parent().toggleClass('bx-menu-tab-active')}
 }
